import 'dotenv/config';
import express from 'express';
import http from 'http';
import { WebSocketServer, WebSocket } from 'ws';
const PORT=Number(process.env.PORT||10000), API_KEY=process.env.TWELVE_DATA_API_KEY||'', SYMBOL=process.env.MARKET_SYMBOL||'XAU/USD';
const HISTORY_SIZE=Math.min(500,Math.max(60,Number(process.env.HISTORY_SIZE||200))), REFRESH_MS=Math.max(30000,Number(process.env.HISTORY_REFRESH_MS||60000));
const VALID_TF=new Set(['5m','15m','30m','1h']), TF_MAP={'5m':'5min','15m':'15min','30m':'30min','1h':'1h'};
const clients=new Set(), cache=new Map(); let upstream=null, reconnectTimer=null, backoff=1000;
const app=express(); app.get('/health',(_q,r)=>r.json({ok:true,upstream:upstream?.readyState===WebSocket.OPEN?'connected':'disconnected',clients:clients.size,symbol:SYMBOL,time:new Date().toISOString()})); app.get('/',(_q,r)=>r.type('text').send('XAUUSD Mobile Signal server OK'));
const server=http.createServer(app), wss=new WebSocketServer({server,path:'/stream'});
const sec=tf=>({'5m':300,'15m':900,'30m':1800,'1h':3600}[tf]||300), bucket=(ms,s)=>Math.floor(ms/1000/s)*s*1000;
const broadcast=o=>{const m=JSON.stringify(o);for(const c of clients)if(c.ws.readyState===WebSocket.OPEN)c.ws.send(m)};
function parseHistory(j,tf){const rows=(j.values||[]).map(v=>({t:Date.parse(v.datetime+'Z'),o:+v.open,h:+v.high,l:+v.low,c:+v.close})).filter(v=>Number.isFinite(v.t)&&[v.o,v.h,v.l,v.c].every(Number.isFinite));const closed=rows.filter(v=>v.t<bucket(Date.now(),sec(tf))).slice(-HISTORY_SIZE);return{opens:closed.map(x=>x.o),highs:closed.map(x=>x.h),lows:closed.map(x=>x.l),closes:closed.map(x=>x.c),times:closed.map(x=>x.t),asOf:closed.length?new Date(closed.at(-1).t).toISOString():null}};
async function history(tf){if(!API_KEY)throw Error('TWELVE_DATA_API_KEY ausente');const u=new URL('https://api.twelvedata.com/time_series');u.searchParams.set('symbol',SYMBOL);u.searchParams.set('interval',TF_MAP[tf]);u.searchParams.set('outputsize',String(HISTORY_SIZE+3));u.searchParams.set('apikey',API_KEY);const r=await fetch(u),j=await r.json();if(!r.ok||j.status==='error'||!Array.isArray(j.values))throw Error(j.message||`Twelve Data HTTP ${r.status}`);const c=parseHistory(j,tf);if(c.closes.length<40)throw Error(`Histórico insuficiente: ${c.closes.length}`);cache.set(tf,{candles:c,at:Date.now()});return c}
async function ensure(tf){const h=cache.get(tf);return h&&Date.now()-h.at<REFRESH_MS?h.candles:history(tf)}
const snap=(c,candles)=>c.ws.send(JSON.stringify({type:'snapshot',symbol:SYMBOL,source:'Twelve Data',price:c.lastPrice??null,candles,ts:Date.now()}));
async function connect(){if(!API_KEY||upstream&&(upstream.readyState===WebSocket.OPEN||upstream.readyState===WebSocket.CONNECTING))return;const ws=new WebSocket(`wss://ws.twelvedata.com/v1/quotes/price?apikey=${encodeURIComponent(API_KEY)}`);upstream=ws;ws.on('open',()=>{backoff=1000;ws.send(JSON.stringify({action:'subscribe',params:{symbols:SYMBOL}}));broadcast({type:'server',status:'upstream_connected',ts:Date.now()})});ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.event==='price'&&Number.isFinite(+m.price)){const price=+m.price,t0=Number(m.timestamp||Date.now()),ts=t0<1e12?t0*1000:t0;for(const c of clients){c.lastPrice=price;if(c.ws.readyState===WebSocket.OPEN)c.ws.send(JSON.stringify({type:'tick',symbol:SYMBOL,price,ts,source:'Twelve Data'}))}}else if(m.event==='error'||m.status==='error')broadcast({type:'error',message:m.message||'Twelve Data erro',ts:Date.now()})}catch{}});ws.on('close',()=>{upstream=null;broadcast({type:'server',status:'upstream_disconnected',ts:Date.now()});clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,backoff);backoff=Math.min(backoff*2,30000)});ws.on('error',e=>console.error('Upstream:',e.message))}
setInterval(()=>{if(upstream?.readyState===WebSocket.OPEN)upstream.send(JSON.stringify({action:'heartbeat'}))},10000);
setInterval(async()=>{for(const tf of new Set([...clients].map(c=>c.tf))){try{const c=await history(tf);for(const x of clients)if(x.tf===tf)snap(x,c)}catch(e){broadcast({type:'error',message:`Histórico ${tf}: ${e.message}`,ts:Date.now()})}}},REFRESH_MS);
wss.on('connection',async ws=>{const c={ws,tf:'5m',lastPrice:null};clients.add(c);ws.on('message',async raw=>{try{const m=JSON.parse(raw);if(m.type==='config'&&VALID_TF.has(m.tf)){c.tf=m.tf;snap(c,await ensure(c.tf))}}catch(e){ws.send(JSON.stringify({type:'error',message:e.message,ts:Date.now()}))}});ws.on('close',()=>clients.delete(c));ws.on('error',()=>clients.delete(c));try{snap(c,await ensure('5m'))}catch(e){ws.send(JSON.stringify({type:'error',message:e.message,ts:Date.now()}))}connect()});
server.listen(PORT,()=>console.log(`XAUUSD server listening on ${PORT}`));
